### ISSUE TITLE
VLC button not showing on latest version of Chrome/Plex on Catalina.

### ISSUE THREAD

**Issue by joshkerr** [soerenkampschroer/plex-to-vlc#1]
I'm running plex 4.22.1 on chrome 79.0.3945.130 and the button isn't showing.

**Comment by soerenkampschroer** [comment]
Thanks for letting me know, I haven't been using it myself for a while. I'll have a look this weekend.

Cheers!

**Comment by fsjack** [comment]
Same issue, checked Content Scripts tab in Chrome did not found the scripts running.

**Comment by soerenkampschroer** [comment]
I've updated the extension, the button is now showing up again. It's in review currently but should be available shortly. I've also attached a new build for the host app, it's pretty much just a re-build with updated dependencies. The extension should prompt you to download the new host app, or you can head over to the release page and download it there 👍

**Comment by zeroziilch** [comment]
This is also happening to me, can't get it to work for the life of me. I have:

Mac osx 10.13.6 high sierra
Chrome: Version 80.0.3987.149 (Official Build) (64-bit)

I have the latest version of plex, I have the desktop app, the media server, and I have your plex to vlc app, I put in the code in the native messaging hosts folder like instructed but the vlc button never shows
