### ISSUE TITLE
REQ: play videos from Plex hosted on another computer.

### ISSUE THREAD

**Issue by joshkerr** [soerenkampschroer/plex-to-vlc#2]
This shouldn't be too hard to do. I can copy the download link from Plex hosted on a server and then paste it into VLC and it plays fine. Could you add the capability to play remote files from Plex via VLC?

**Comment by soerenkampschroer** [comment]
It should work now. Playback defaults to the local file if it's there, otherwise it's using the download link. I could only test it on my local machine, so let me know if it works on a real network source.

New host app is in releases, chrome extension is in review (should be up shortly).

Cheers!

**Comment by porg** [comment]
I experienced this as NOT working.

## Had installed the manual way
- /Applications/plex-to-vlc.app (Electron based app)
- Chrome extension
- JSON config file copied to: `~/Library/Application Support/Google/Chrome/NativeMessagingHosts/`

## With this LAN / Plex setup
- Plex running on NAS, at hostname:port being mynas.local:32400
- Plex video files are on that NAS too
- In this scenario my Mac is purely a client running the Chrome web browser with the extension plex-to-vlc, which is activated and got granted all permissions it may asked for.

## Reproduction
1. Mac Chrome opens the Plex-URL `http://mynas.local:32400`
2. Navigate to video of my liking, did not find button "Play with VLC"
3. Launched companion app `/Applications/plex-to-vlc.app` manually (the manual says nothing on this, so I guess this is not required, but I at least tried)
4. With the companion app opened, I tried 1-2 again: Launched Chrome again and opened the Plex URL again. Nothing.
5. Looked at DevTools > Console > Says something like "Cannot access loopback device 127.0.0.0:32400" not verbatim, but in that spirit.
- The `:32400` is the Plex port. This tells me it expects Plex to run on the local machine (=127.0.0.0).

So this feature seems to be NOT implemented to me.

- However I found a more viable alternative anyhow: #51
