### ISSUE TITLE
Could "Play with external video player" be implemented as a server side Plex plugin/modification which would then work in any Mac web browser?

### ISSUE THREAD

**Issue by porg** [soerenkampschroer/plex-to-vlc#38]
## Analysis of the status quo
- Your plugin works client side as a browser extension.
- The downside of this is that on any end device I wanna use it I do not only need a web browser but also that extension.

## Idea
1) Does Plex provide a plugin/hooking functionality so that your "Play with …" button could be generated server side?
    - If yes, then client side you would need no installation at all which would work with any Mac web browser, also Safari.
2) B/c then you would need just to transform a filepath to an URL scheme which the Mac hands over to a particular video playing app and the app handler on the Mac would take over (after Safari/macOS first asks whether you want to grant access to open URLs of that kind with app X). Or possibly use a MIME type or UTI (Uniform Type Identifier) which targets a particular video player.

**Comment by soerenkampschroer** [comment]
Thank you for raising this issue. Unfortunately [Plex discontinued plugin support in 2018](https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/). While it might still be possible to add things to the plugin folder I'm not sure how long it will be. I'm also not sure if there is any documentation still available so I wouldn't know where to start.

I do appreciate you taking the time and sharing ideas. I sometimes forget other people are using the extension as well as it was mainly just a little personal project for myself to solve a problem. Let me know if there is anything else you would want changed or added.

Cheers!

**Comment by porg** [comment]
Thanks for your offer, but the possibility of a Plex server side "Play with …" plugin was the request, and as Plex plugin support was officially discontinued, I think there's nothing more that I could ask for. Thanks!
