### ISSUE TITLE
Plex link still does not show up for me after installing the latest version

### ISSUE THREAD

**Issue by joshkerr** [soerenkampschroer/plex-to-vlc#4]
I'm running latest Chrome on latest MacOS, latest plex server running on Linux. I've installed the companion app.

**Comment by joshkerr** [comment]
<img width="1785" alt="Screen Shot 2020-04-06 at 12 17 46 PM" src="https://user-images.githubusercontent.com/17816/78586217-bfb71000-7800-11ea-8569-2ab808fbb160.png">

**Comment by soerenkampschroer** [comment]
Can't reproduce, button shows up in Plex Server Version 1.19.1.2645 (latest). Make sure to also install the Chrome extension from here:

https://chrome.google.com/webstore/detail/plex-to-vlc/admjkihehbkklbidlcpmjcaplbkngeed

**Comment by joshkerr** [comment]
Chrome extension was installed from there. Still doesn’t show up for me.

**Comment by soerenkampschroer** [comment]
Not sure what the problem could be honestly. Try updating Plex Server and see if it helps. If not I'd need the versions of your Plex Server and Chrome. Also check the version of the Chrome extension and trigger a manual update. Sometimes Chrome doesn't keep things updated on it's own.
