### ISSUE TITLE
VLC button no longer showing

### ISSUE THREAD

**Issue by DoubleZeroziilch** [soerenkampschroer/plex-to-vlc#5]
It was working for a while, now its not working, the VLC button is no longer there, I just updated chrome and the extension and its still not working after turning chrome and the companion app off and back on. Not sure what I did or whats going wrong here. Or maybe theres some trick I'm missing to re-engage it.

Here are my versions:

Google Chrome is up to date:
Version 81.0.4044.122 (Official Build) (64-bit)

Plex to VLC Extension:
1.3.0

Plex to Vlc companion app:
Version 1.3.0 (1.3.0)

Mac Operating system:
10.13.6 (17G7024)

**Comment by soerenkampschroer** [comment]
I tested it on the latest plex server version and it works fine for me. Please check your plex server version and update to the latest release. If that doesn't help I'd need the server version you are on so I can look into it. But that should be why it's not showing up.
